### ISSUE TITLE
Setup Git-Lfs

### ISSUE THREAD

**Issue by Saarg** [Kwarthys/RepoJeuVideo#2]
Git est pas fait pour les fichiers binaires volumineux (fbx, png, jpg...) il vaut mieux setup git-lfs: https://git-lfs.github.com/

en version gratuite la limite de data est vite passée et il faut payer un data pack pour la faire monter a 50GB ça coûte 5$

**Comment by Kwarthys** [comment]
![image](https://user-images.githubusercontent.com/10401636/73836804-60448000-4810-11ea-9ceb-e42150d7d079.png)

Un fichier gitattributes à été ajouté, c'est suffisant pour que lfs puisse faire sa popote ?

**Comment by Saarg** [comment]
yup il faut que les gens qui utilisent le repo aient git-lfs d’installé. Si vous utiliser sourcetree comme gui git il vous propose ça tout seul et vous indique quand un fichier est trop gros et devrait etre dans git-lfs. 
Attention a ne pas mettre les .unity, .prefab et .asset dans le gitattribute
